version: '3.3'
services:
    gpsutil:
        build: ./gpsUtils/DockerFile
        restart: always
        ports: 
            - "8081:8081"
        container_name: gpsutil
    # trippricer:
    #     build: ./TripPricer/
    #     restart: always
    #     ports: 
    #         - "8082:8080"
    #     container_name: trippricer
    # rewardcentral:
    #     build: ./RewardCentral/
    #     restart: always
    #     ports: 
    #         - "8083:8080"
    #     container_name: rewardcentral