version: '3.3'
services:
    gpsutil:
        build: ./gpsUtils/DockerFile
        restart: always
        ports: 
            - "8081:8081"
        container_name: gpsutil
    rewardcentral:
        build: ./RewardsService/DockerFile
        restart: always
        ports: 
           - "8082:8082"
        container_name: rewardCentral
    trippricer:
        build: ./TripPricer/DockerFile
        restart: always
        ports: 
            - "8083:8083"
        container_name: trippricer